version: '3.8'
services:
  app:
    image: boot-image
    container_name: oj-timer-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/oj_timer?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}

    env_file:
      - ./.env

    ports:
      - "8080:8080"
    networks:
      - oj-timer-network

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - app

    networks:
      - oj-timer-network

networks:
  oj-timer-network:
    external: true