spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#            format_sql: true
#      generate-ddl: true

    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 2000
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  web:
    resources:
      static-locations: classpath:/static/
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${GOOGLE_EMAIL}
#    password: ${GOOGLE_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          timeout: 20000
#          starttls:
#            enable : true
#            required : true
#          connectiontimeout : 20000
#          writetimeout: 20000
#    auth-code-expiration-millis: 300000 # 5 * 60 * 1000
  jackson:
    time-zone: Asia/Seoul

server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

logging:
  level:
    sql: trace


