spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
            format_sql: true
#      generate-ddl: true

    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    sql: trace