spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#            format_sql: true
#      generate-ddl: true

    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#  data:
#    web:
#      pageable:
#        default-page-size: 20
#        max-page-size: 2000

server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

logging:
  level:
    sql: trace