on:
  workflow_dispatch: # 수동 실행 가능

jobs:

  deploy:
    runs-on: ubuntu-latest

    permissions:
      write-all
    steps:
      - uses: actions/checkout@v4


      - name: Deploy to server
        uses: appleboy/ssh-action@master
        id: deploy
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          port: 22
          key: ${{ secrets.KEY }}
          script: |
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            cd ${{ secrets.PROJECT_PATH }}
            
            rm ./docker-compose.yml 
            rm ./env
            rm -rf default.conf
            
            echo "${{ secrets.DOCKER_COMPOSE }}" >> ./docker-compose.yml
            
            echo "${{ secrets.ENV_FILE }}" >> ./.env
            
            printf "%s" "${{ secrets.DEFAULT_CONF }}" > ./default.conf
            
            sudo docker compose down
            
            sudo docker container rm ${{ secrets.SERVER_NAME }} nginx-server
            
            sudo docker pull ${{ secrets.DOCKER_IMAGE_NAME }}
            
            sudo docker compose -f docker-compose.yml up -d
