on:
  workflow_dispatch: # 수동 실행 가능

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Test SSH Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          port: 22
          key: ${{ secrets.KEY }}
          script: |
            echo "✅ SSH 접속 성공!"
            hostname
            uptime
            whoami
            ls -l